"""empty message

Revision ID: 3644ad4a70be
Revises: 53cc8916863c
Create Date: 2020-10-21 16:15:01.156660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3644ad4a70be'
down_revision = '53cc8916863c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('street', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'street')
    # ### end Alembic commands ###
