"""empty message

Revision ID: dbf5e5a0f773
Revises: f6f2682d6999
Create Date: 2020-10-22 20:52:00.513394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbf5e5a0f773'
down_revision = 'f6f2682d6999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'patients', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='unique')
    # ### end Alembic commands ###
